export type OfficialPraiseTrack = {
  id: string
  title: string
  artist: string
}

export const officialPraiseTracks: OfficialPraiseTrack[] = [
  ['dL-XAmNtJLA', '내 맘에 주를 위한 자리', '아가파오 워십'],
  ['4RRxhqKsTA8', '사랑을 나눠요 (Acoustic Ver.)', 'WELOVE CREATIVE TEAM'],
  ['VEUQfvv4WNw', 'Conquering the Dark Night', 'WECCLESIA 위클레시아'],
  ['pqDTRgaY8q0', '고요한 밤 하늘 별들 반짝일 때 Savior Has Come', '팀룩워십'],
  ['nS9Vul0VOqM', '사랑한다 말하시네', 'GIFTED'],
  ['V2RnPmCuufU', 'Praising the Lord, the Reason For My Life', 'WECCLESIA 위클레시아'],
  ['lV3zSKZYdEQ', 'I Am Weak In Myself', 'WECCLESIA 위클레시아'],
  ['PMTST3gtBjc', 'Dan. 3:18', 'GIFTED'],
  ['LYD-1x04Qig', 'Hey Buddy', 'GIFTED'],
  ['fjyzLK7fdJc', 'Broken Hearted Worshiper', 'WELOVE CREATIVE TEAM'],
  ['4RSPMb6DkR8', '예수를 나의 구주 삼고', '나비워십'],
  ['dqkjYU651LY', '나는 주만 높이리', '마커스워십'],
  ['ujZT26KzxQY', '주가 지으신 이날에 Today is the Day', '팀룩워십'],
  ['OyPlxLePdDc', '주를 찾는 모든 자들이 (시편 70편) Those Who Seek the Lord', '팀룩워십'],
  ['KM1DjMPdsXc', '하늘 소망', '어노인팅'],
  ['770mFGCCTDg', '내 마음을 가득 채운', 'WELOVE CREATIVE TEAM'],
  ['_r4zDp0CS1E', '내 영혼이', '꿈이 있는 자유'],
  ['FO8Aa-qu8HA', '빛을 들고 세상으로', '어노인팅'],
  ['c216NU8183o', '영접송 (내 맘을 엽니다)', '팀룩워십'],
  ['H56xVRKQ2Ag', '주와 함께 걸어가네 (Live) Walking With The Lord', '팀룩워십'],
  ['gaG8xq_tQXA', '주와 함께 걸어가네 Walking With The Lord', '팀룩워십'],
  ['qy3z987E-P8', 'Looking At The Lord', 'GIFTED'],
  ['sQN1IgfJXKs', '혼자 걷지 않을 거예요', '예람워십'],
  ['z2D-pt0IKdY', '선하신 나의 주', '팀룩워십'],
  ['yf6RQOOwRPA', '모든 걸음 되시네', '예람워십'],
  ['SNdlDao8Q1M', 'Rise Again', 'WELOVE CREATIVE TEAM'],
  ['gQq1UJ3OKOk', '그리스도 안에서', '팀룩워십'],
  ['mrjRlnrhoYs', '주님 마음 내게 주소서', '마커스워십'],
  ['LaO19EbMzcE', '주 은혜임을', '마커스워십'],
  ['hAJNiYuiUww', '주의 사랑 우리 안에', '어노인팅'],
  ['COV8-ZlfZPg', '내 주를 가까이', '제이어스 J-US'],
  ['PRlEqQJ9c10', '우린 주를 만나고', '어노인팅'],
  ['9WcgtGvRe5Q', 'On Your Day', 'WELOVE CREATIVE TEAM'],
  ['2S-GvD-GtNs', 'His Light (I Am)', 'WELOVE CREATIVE TEAM'],
  ['JzJcFbHRCEM', 'Where Your Hand May Reach', 'WELOVE CREATIVE TEAM'],
  ['NNw5HahlYpQ', 'Lost in the Dark', 'WELOVE CREATIVE TEAM'],
  ['4KouWV1sYPs', 'Darkness to Light', 'WELOVE CREATIVE TEAM'],
  ['sqdesWPn3eA', 'Praise Him', 'WELOVE CREATIVE TEAM'],
  ['U1YJM2rlNpo', '주는 완전합니다', '마커스워십'],
  ['Yqod83GKE0M', '예수, 늘 함께 하시네', '마커스워십'],
  ['I-i2yA1e5F4', 'Come And Let Us Go', 'WELOVE CREATIVE TEAM'],
  ['RdtAYWGw98E', '그 안에 나 거하네', '마커스워십'],
  ['MDtchqosJX8', '우리 주 하나님 + 그 크신 하나님의 사랑', '예람워십'],
  ['jPqZ18zYVIM', '내가 늘 의지하는 예수', '어노인팅'],
  ['P7pGWTD8Wvc', '한나의 노래', '마커스워십'],
  ['4v0oHeJ8-2k', '예수, 늘 함께 하시네 (Official)', '마커스워십'],
  ['yo0HQn_NCyY', 'The Love of God Is Greater Far', '아이자야씩스티원'],
  ['Ctl6Q1t_OSQ', '내 모습 이대로', '제이어스 J-US'],
  ['4msV_nz-xw0', '나의 기쁨 나의 소망되시며', '어노인팅'],
  ['k4Md9dFbky0', 'The Lord Has Called Me', 'WELOVE CREATIVE TEAM'],
  ['QlwG8Rub5a8', '하늘에 닿아도 (시편 73편)', '어노인팅'],
  ['uecwkxY9tiY', '어둔 날 다 지나고', 'WELOVE CREATIVE TEAM'],
  ['I7pCmfut__I', '생명의 양식', '어노인팅'],
  ['ufD_Ov6umK4', '푯대를 향하여', '어노인팅'],
  ['Bvx01WxiAso', '나의 소망 되신 주', '어노인팅'],
  ['6tqBtZbn6kU', '자랑 Psalm 34', '예수전도단'],
  ['0wcTqurzRdI', '새 힘 얻으리 (Electric Guitar)', '3:16 Worship'],
  ['5N2R8lNNBJ4', '새 힘 얻으리', '파워스테이션'],
  ['ZvINdEeqcUs', '새 힘 얻으리', '어노인팅'],
  ['tfYVlfR3DEA', '예수님을 향한 이 노래', '꿈이 있는 자유'],
  ['Hgdk1aIyT08', '전해야 해', '꿈이 있는 자유'],
  ['16G7beqQmmQ', '그 마음을 지닌 자', '꿈이 있는 자유'],
  ['Y6YMcfzgJ90', '하연이에게', '꿈이 있는 자유'],
  ['T5xHJeK7EfM', '이 땅에 오직', '꿈이 있는 자유'],
  ['0l6AibVuMO0', '신부', '어노인팅'],
  ['tE_CKrZufSk', '시편의 노래', '어노인팅'],
  ['4e_2RYwheMU', '그 사랑 감사해', '제이어스 J-US'],
  ['3j9blU6yGiI', '요셉의 노래', 'AJ Worship'],
  ['pt928N-Treg', '예수 따라가며', '어노인팅'],
  ['Guzz5-m9O_E', '예수 안에 소망있네', '어노인팅'],
  ['a55aLhz7Zow', '주 사랑이 나를 숨쉬게 해', '어노인팅'],
  ['9RgepmRUshA', '더 낮은 곳으로 흘러', '어노인팅'],
  ['8Es1WmloSss', '빛나는 유산 (시편 16편)', 'WELOVE CREATIVE TEAM'],
  ['Yc7do4CqsoU', '예배하는 이들에게', 'WELOVE CREATIVE TEAM'],
  ['8vyncunFqjk', '손에 쥔 걸 놓고서', 'WELOVE CREATIVE TEAM'],
  ['lZ93dClPekM', '모든 계절에 모든 시간에', 'WELOVE CREATIVE TEAM'],
  ['AGMnGU_fPv8', 'At Your Ocean(주님의 바다에)', 'WELOVE CREATIVE TEAM'],
  ['DQdW9tHve4U', 'Let Us Go To His Ocean(바다로 가자)', 'WELOVE CREATIVE TEAM'],
  ['hCt46uL6IXo', 'Guest (We Flowed Here and Flow Back)(객 (흘러왔다 흘러가네))', 'WELOVE CREATIVE TEAM'],
  ['oF-6BK0TkTw', 'Flow and Flow (feat. Anandelight)(흘러 흘러 (feat. 아넌딜라이트))', 'WELOVE CREATIVE TEAM'],
  ['tCyIkG3QTwU', '빈 무덤 (Live)', 'WELOVE CREATIVE TEAM'],
  ['SgCkAThFdrw', '소울메이트 (Live)', 'WELOVE CREATIVE TEAM'],
  ['Htiplroe8wc', '소생 (우린 살아났으니) (Live)', 'WELOVE CREATIVE TEAM'],
  ['7cJGO3WkFuI', '본향을 향해 (Live)', 'WELOVE CREATIVE TEAM'],
  ['Dq74PzQGTa0', '나의 꿈, 내 소망 (Live)', 'WELOVE CREATIVE TEAM'],
  ['DurYvijNaz0', '야훼 (Live)', 'WELOVE CREATIVE TEAM'],
  ['Xc5yi8idy7I', '주님 난 알고 싶어요 (Acoustic Ver.)', 'WELOVE CREATIVE TEAM'],
  ['iSuuAeRNgwA', '자유를 선포해 Freedom We Proclaim', '팀룩워십'],
  ['RLJfBe1dTJQ', '찬양해 그 이름 Praise His Name', '팀룩워십'],
  ['ShcrG8ENGpY', '우리를 사랑하시는 이로 말미암아', '팀룩워십'],
  ['aOkyVw-AxJk', 'We Will Never Stop', '팀룩워십'],
  ['85VCY_OsPJk', '생명의 말씀 The Word of Life', '팀룩워십'],
  ['QhgLvDLmrYk', '나는 너를 만나고 Ever Since I Met You', '팀룩워십'],
  ['dq3yJ350s2c', '나 주님을 모른다 하여도 His Faithfulness', '팀룩워십'],
  ['EsF5q_JmsMQ', '주를 더욱 사랑 JESUS I LOVE YOU MORE (Live from TLMW)', '팀룩워십'],
  ['5EHhJZiFpE0', '끝까지 남겠네 The Justice Song', '팀룩워십'],
  ['hYw08KqzKrw', '함께 지어져 가네 Being Built Together', '팀룩워십'],
  ['HCCg6a0Gttc', '나는 주만 높이리', '나비워십'],
  ['9i4QINlSyfI', '불을 내려 주소서', '나비워십'],
  ['uzYI1jIw_LQ', '주 이름 찬양', '나비워십'],
].map(([id, title, artist]) => ({ id, title, artist }))
