'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { officialPraiseTracks as songs } from '@/lib/officialPraiseTracks'

type Track = { id: string; rank: number; youtube_id: string; title: string; artist: string; is_active: boolean }

export default function Top100Editor({ tracks }: { tracks: Track[] }) {
  const router = useRouter()
  const [message, setMessage] = useState('')
  async function call(body: object) { const response = await fetch('/api/admin/config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); setMessage(response.ok ? '저장했습니다.' : result.error); if (response.ok) router.refresh() }
  async function submit(event: FormEvent<HTMLFormElement>, id?: string) { event.preventDefault(); const form = new FormData(event.currentTarget); await call({ action: 'upsert-track', id, rank: form.get('rank'), youtubeId: form.get('youtubeId'), title: form.get('title'), artist: form.get('artist'), isActive: true }) }
  return <div className="space-y-4"><button onClick={() => call({ action: 'seed-tracks', tracks: songs })} className="min-h-12 w-full rounded-[14px] bg-[var(--ub-color-brand)] font-semibold text-white">공식 찬양팀 TOP 100으로 교체</button><form onSubmit={(event) => submit(event)} className="grid grid-cols-[64px_1fr] gap-2 rounded-[18px] bg-[var(--ub-surface-card-strong)] p-3 text-[var(--ub-text-primary)]"><input name="rank" type="number" min="1" max="100" placeholder="순위" className="rounded-lg bg-[var(--ub-surface-muted)] px-2" /><div className="space-y-2"><input name="youtubeId" placeholder="YouTube ID" className="min-h-10 w-full rounded-lg bg-[var(--ub-surface-muted)] px-3" /><input name="title" placeholder="곡명" className="min-h-10 w-full rounded-lg bg-[var(--ub-surface-muted)] px-3" /><input name="artist" placeholder="아티스트" className="min-h-10 w-full rounded-lg bg-[var(--ub-surface-muted)] px-3" /><button className="min-h-10 w-full rounded-lg bg-[var(--ub-color-brand)] text-white">곡 추가</button></div></form>{tracks.map((track) => <form key={track.id} onSubmit={(event) => submit(event, track.id)} className="grid grid-cols-[56px_1fr] gap-2 rounded-[18px] bg-[var(--ub-surface-card-strong)] p-3 text-[var(--ub-text-primary)]"><input name="rank" type="number" defaultValue={track.rank} className="rounded-lg bg-[var(--ub-surface-muted)] px-2" /><div className="space-y-2"><input name="youtubeId" defaultValue={track.youtube_id} className="min-h-9 w-full rounded-lg bg-[var(--ub-surface-muted)] px-3 text-[12px]" /><input name="title" defaultValue={track.title} className="min-h-9 w-full rounded-lg bg-[var(--ub-surface-muted)] px-3 text-[13px]" /><input name="artist" defaultValue={track.artist} className="min-h-9 w-full rounded-lg bg-[var(--ub-surface-muted)] px-3 text-[13px]" /><div className="flex gap-2"><button className="min-h-9 flex-1 rounded-lg bg-[var(--ub-color-brand)] text-white">저장</button><button type="button" onClick={() => call({ action: 'delete-track', id: track.id })} className="min-h-9 rounded-lg bg-[#FF3B30]/10 px-3 text-[#FF3B30]">삭제</button></div></div></form>)}{message && <p className="sticky bottom-4 rounded-full bg-black/80 px-4 py-3 text-center text-[13px] text-white">{message}</p>}</div>
}
